---
name: Main

'on':
  repository_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  ansible-linter:
    name: Ansible Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ansible-lint Dependencies
        run: pip3 install ansible ansible-base ansible-lint

      - name: Lint Code Base with ansible-lint
        run: ansible-lint

  super-linter:
    name: Github Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base with github super-linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: '.*.md'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  yaml-linter:
    name: YAML Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yamllint Dependencies
        run: pip3 install yamllint

      - name: Lint Code Base with yamllint
        run: yamllint .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Molecule Dependencies
        run: pip3 install -r requirements.txt

      - name: Install ansible Dependencies
        run: ansible-galaxy role install -r roles/requirements.yml

      - name: Run Playbook
        run: ansible-playbook -i hosts playbook.yml
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
  release:
    name: Release
    if: ${{ github.event_name != 'repository_dispatch' }}
    runs-on: ubuntu-latest
    needs:
      - ansible-linter
      - super-linter
      - yaml-linter
      - test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create a new tag
        uses: phish108/autotag-action@1.1.37
        id: autotag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.autotag.outputs.new-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install ansible-base
        run: pip3 install ansible-base

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import
          --token "${{ secrets.GALAXY_API_KEY }}"
          --branch main
          "$(echo ${{ github.repository }} | cut -d/ -f1)"
          "$(echo ${{ github.repository }} | cut -d/ -f2)"

  notify:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - release
    steps:
      - name: Notify Slack channel on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/ckaserer/logos/raw/master/ansible.png
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: '#ff0033'
          SLACK_FOOTER: ''
...
